extension["即时乱斗"]={
    author:"Show-K",
    intro:"实验：（伪）即时回合制玩法",
    size:"962KB",
    netdisk:"",
    version:"1.1",
    files:[
        "extension.js",
        "pinyin_dict_notone.js",
        "pinyin_dict_polyphone.js",
        "pinyinUtil.js"
	]
};

extension["在线更新"]={
    author:"诗笺、Show-K（未经许可修改）",
    intro:"点击按钮即可在线更新，文件下载失败会自动重新下载。</br><span style='color:red'>※请不要在更新时关闭游戏或主动断网，否则后果自负</span></br>最新完整包下载地址：<a target='_self' href='https://hub.fastgit.org/Show-K/noname/archive/refs/heads/super_smash_tabletop.zip'><span style='text-decoration: underline;'>点击下载</span></a>",
    size:"48.6KB",
    netdisk:"",
    version:"1.26SST",
    files:[
        "extension.js"
	]
};
/*
extension["拖拽读取"]={
    author:"诗笺、Show-K（未经允许修改）",
    intro:"windows电脑版专属扩展，把zip或7z文件（离线包，扩展或素材压缩包，目前不支持导入7z扩展）拖入到游戏内即可导入",
    size:"#SIZE",
    netdisk:"",
    version:"1.77SST"
};
*/